name: CI/CD 

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login docker.io
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build accuracy
      run: |
        docker build ./accuracy -t rajasirpi/sketchmapia-2.0/accuracy:1.0.0 
    - name: docker build completeness
      run: |
        docker build ./completeness -t rajasirpi/sketchmapia-2.0/completeness:1.0.0
    - name: docker build generalizations
      run: |
        docker build ./generalizations -t rajasirpi/sketchmapia-2.0/generalizations:1.0.0
    - name: docker build sketchmap_analyser
      run: |
        docker build ./sketchmap_analyser -t rajasirpi/sketchmapia-2.0/sketchmap_analyser:1.0.0
    - name: docker push
      run: |
        docker push rajasirpi/sketchmapia-2.0/accuracy:1.0.0
        docker push rajasirpi/sketchmapia-2.0/completeness:1.0.0
        docker push rajasirpi/sketchmapia-2.0/generalizations:1.0.0
        docker push rajasirpi/sketchmapia-2.0//sketchmap_analyser:1.0.0

        

